---
# tasks file for keystone
- name: Create KeyStone Database
  mysql_db: name=keystone state=present
  delegate_to: "{{ groups['database-servers'][0] }}"
  run_once: true
  become: true

- name: Create KeyStone User (%)
  mysql_user: name='keystone' host={{ ansible_fqdn }} state=present password={{ KEYSTONE_DBPASS }} priv=keystone.*:ALL
  become: true
  delegate_to: "{{ groups['database-servers'][0] }}"
  run_once: true
  with_items: groups['keystone']

- name: Disable Keystone auto-starting after installation
  command: 'echo "manual" > /etc/init/keystone.override'
  become: true

- name: Install Apt Packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  become: true
  with_items:
    - keystone
    - apache2
    - libapache2-mod-wsgi

- name: Configure Keystone
  template: src=keystone.conf.j2 dest=/etc/keystone/keystone.conf
  become: true

- name: Populate identity service database
  command: '/bin/sh -c "keystone-manage db_sync" keystone'
  become: true
  run_once: true

- name: Initiating Fernet Keys
  command: "keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone"
  become: true

- name: Check for any default vhosts (sites-available)
  shell: "ls -1 /etc/apache2/sites-available/*default*.conf"
  register: sites-available
  ignore_errors: true
  become: true

- name: Clear other default vhosts (sites-available)
  file: path="{{ item }}" state=absent
  with_items: sites-available.stdout_lines
  become: true
  ignore_errors: true
  notify: restart apache2

- name: Check for any default vhosts (sites-enabled)
  shell: "ls -1 /etc/apache2/sites-enabled/*default*.conf"
  register: sites-enabled
  ignore_errors: true
  become: true

- name: Clear other default vhosts (sites-enabled)
  file: path="{{ item }}" state=absent
  with_items: sites-enabled.stdout_lines
  become: true
  ignore_errors: true
  notify: restart apache2

- name: Configure Apache2
  template: src=apache2.conf.j2 dest="/etc/apache2/apache2.conf"
  become: true
  notify: restart apache2

- name: Remove ports.conf
  file: path=/etc/apache2/ports.conf state=absent
  become: true
  notify: restart apache2

- name: Create wsgi-vhosts
  template: src=wsgi-keystone.conf.j2 dest="/etc/apache2/sites-available/wsgi-keystone.conf"
  become: true
  notify: restart apache2

- name: Enable site (link)
  file: src="/etc/apache2/sites-available/wsgi-keystone.conf" path="/etc/apache2/sites-enabled/wsgi-keystone.conf" state=link
  become: true
  notify: restart apache2

- name: delete sqlite database
  file: path="/var/lib/keystone/keystone.db" state=absent
  become: true

- name: Create API Endpoints
  command: "{{ item }}"
  become: true
  environment: "{{ proxy_env }}"
  run_once: true
  register: command_output
  failed_when: "'error' in command_output.stderr"
  with_items:
    - 'openstack service create --name keystone --description "OpenStack Identity" identity'
    - 'openstack endpoint create --region RegionOne identity public http://{{ openstack_cluster_domain }}:5000/v3'
    - 'openstack endpoint create --region RegionOne identity internal http://{{ openstack_cluster_domain }}:5000/v3'
    - 'openstack endpoint create --region RegionOne identity admin http://{{ openstack_cluster_domain }}:35357/v3'

- name: Create Roles/Users/Projects/Domains
  command: "{{ item }}"
  become: true
  environment: "{{ proxy_env }}"
  run_once: true
  register: command_output
  failed_when: "'error' in command_output.stderr"
  with_items:
    - 'openstack domain create --description "Default Domain" default'
    - 'openstack project create --domain default --description "Admin Project" admin'
    - 'openstack user create --domain default admin --password {{ ADMIN_PASS }}'
    - 'openstack role create admin'
    - 'openstack role add --project admin --user admin admin'
    - 'openstack project create --domain default --description "Service Project" service'
    - 'openstack project create --domain default --description "Demo Project" demo'
    - 'openstack user create --domain default demo --password {{ DEMO_PASS }}'
    - 'openstack role create user'
    - 'openstack role add --project demo --user demo user'

# - name: Modify Keystone-paste.ini (remove admin_token_auth frpm public/admin/v2 apis)
#   replace: dest=/etc/keystone/keystone-paste.ini regexp=" admin_token_auth " replace=" "
#   become: true

- name: Drop admin-openrc in root home
  template: src=admin-openrc.j2 dest=/root/admin-openrc
  become: true
