---
# tasks file for controller-cluster-base
- name: Install Controller Cluster Base Apt Packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  become: true
  with_items:
    - keepalived
    - haproxy

- name: Configure keepalived(VRRP)
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
  notify: restart keepalived
  become: true

- name: Poke keepalived(VRRP)
  command: "keepalived -d"
  become: true

- name: Modify sysctl.conf to allow for VRRP binding
  lineinfile: dest=/etc/sysctl.conf line="net.ipv4.ip_nonlocal_bind=1"
  notify: update sysctl
  become: true

- name: Configure haproxy
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  become: true
  notify: restart haproxy

- name: Ensure haproxy is started
  service: name=haproxy state=started
  become: true
