---
- name: Deploy Jumphost
  hosts: localhost
  vars:
    proj_name: "basic ngnix with php deployment"
    user: "{{ ansible_ssh_user }}"

  tasks:
    - name: Installing Apt Packages
      apt:
        pkg={{ item }}
        update_cache=yes
        cache_valid_time=3600
      with_items:
        - git
        - python3
        - python3-dev
        - python3-pip
        - python3-setuptools
        - vagrant
        - nano
        - screen
      sudo: true
