ENV['VAGRANT_DEFAULT_PROVIDER'] = 'vcenter'
secret = YAML.load_file(".secret.yaml")
node = { hostname: "Ubuntu/Trusty64 - Jumphost",
             box: 'ubuntu/trusty64',
             ip: "10.2.20.10",
             mask: "255.255.255.0",
             gw: "10.2.20.1",
             dns_server_list: ['10.2.10.2', '8.8.8.8'],
             dns_suffix_list: ['lab.sugrue.ca'],
             mem: 1024,
             cpu: 1 }


Vagrant.configure('2') do |config|

  config.vm.provider :vcenter do |vcenter|
    vcenter.hostname = 'vcenter.sugrue.ca'
    vcenter.username = secret['username']
    vcenter.password = secret['password']
    #vcenter.folder_name = ''
    vcenter.datacenter_name = 'Datacenter'
    vcenter.computer_name = 'esxi.c220.oshawa.sugrue.ca'
    vcenter.datastore_name = 'C220 - SAS - RAID 6'
    vcenter.network_name = 'VLAN 2200 - Dev Servers'
    vcenter.linked_clones = true
  end

  config.vm.define node[:hostname] do |node_config|
    node_config.vm.box = node[:box]
    node_config.vm.hostname = node[:hostname]

    # Let's configure the network for the VM, only the ip changes and is
    # coming from the nodes array
    node_config.vm.network :public_network,
                           ip: node[:ip],
                           netmask: node[:mask],
                           gateway: node[:gw],
                           dns_server_list: node[:dns_server_list],
                           dns_suffix_list: node[:dns_suffix_list]

    # Let's override some provider settings for specific VMs
    node_config.vm.provider :vcenter do |override|
      # Override number of cpu and memory based on what's in the nodes array
      override.num_cpu = node[:cpu]
      override.memory = node[:mem]
    end
    node_config.nfs.functional = false
  end
end
